version: '3'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: main_service
      POSTGRES_USER: rest_api
      POSTGRES_PASSWORD: '${MAIN_SERVICE_PASSWORD}'

  postgres_tasks:
    image: postgres:latest
    environment:
      POSTGRES_DB: tasks_service
      POSTGRES_USER: grpc
      POSTGRES_PASSWORD: '${TASKS_SERVICE_PASSWORD}'

  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.4
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181

  kafka:
    image: bitnami/kafka:latest
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9092,OUTSIDE://localhost:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9092,OUTSIDE://0.0.0.0:9093
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  user_service:
    build:
      context: .
      dockerfile: api/Dockerfile
    ports:
      - "5100:5100"
    depends_on:
      - postgres
      - kafka
    restart: on-failure:10  # because of slow postgres init
    environment:
      DATABASE_URI: 'postgresql://rest_api:${MAIN_SERVICE_PASSWORD}@postgres:5432/main_service'
      GRPC_SERVICE: 'tasks_service:50051'
      KAFKA_SERVICE: 'kafka:9092'
    env_file:
      - .env
    platform: linux/amd64

  tasks_service:
    build:
      context: .
      dockerfile: grpc_service/Dockerfile
    ports:
      - "50051:50051"
    depends_on:
      - postgres_tasks
    restart: on-failure:10  # because of slow postgres init
    environment:
      DATA_SOURCE: 'host=postgres_tasks port=5432 user=grpc password=${TASKS_SERVICE_PASSWORD} dbname=tasks_service sslmode=disable'
    env_file:
      - .env
