openapi: 3.0.0
info:
  title: User Service API
  version: 1.0.0
paths:
  /users/register:
    post:
      summary: Register a new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
                first_name:
                  type: string
                last_name:
                  type: string
                birth_date:
                  type: string
                  format: date
                email:
                  type: string
                  format: email
                phone_number:
                  type: string
                  pattern: '^\+?\d+$'
              required:
                - username
                - password
                - first_name
                - last_name
                - birth_date
                - email
                - phone_number
      responses:
        '201':
          description: User registered successfully
        '400':
          description: Bad request, missing or invalid parameters
        '401':
          description: User already exists

  /users/update:
    put:
      summary: Update user data
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                user_id:
                  type: integer
                first_name:
                  type: string
                last_name:
                  type: string
                birth_date:
                  type: string
                  format: date
                email:
                  type: string
                  format: email
                phone_number:
                  type: string
                  pattern: '^\+?\d+$'
              required:
                - user_id
      responses:
        '200':
          description: User updated successfully
        '400':
          description: Bad request, missing or invalid parameters
        '401':
          description: Invalid or expired token
        '404':
          description: User not found

  /users/login:
    post:
      summary: Authenticate user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
              required:
                - username
                - password
      responses:
        '201':
          description: User authenticated successfully
        '401':
          description: Unauthorized, invalid credentials

  /tasks:
    post:
      summary: Create a task
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                content:
                  type: string
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  title:
                    type: string
                  content:
                    type: string
        '401':
          description: Invalid or expired token
        '500':
          description: Internal error
  /tasks/{task_id}:
    get:
      summary: get task by id
      parameters:
        - in: path
          name: task_id
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  title:
                    type: string
                  content:
                    type: string
        '401':
          description: Invalid or expired token
        '500':
          description: Internal error
    put:
      summary: Update a task
      parameters:
        - in: path
          name: task_id
          required: true
          schema:
            type: integer
        - in: query
          name: title
          required: true
          schema:
            type: string
        - in: query
          name: content
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  title:
                    type: string
                  content:
                    type: string
        '401':
          description: Invalid or expired token
        '500':
          description: Internal error
    delete:
      summary: Delete a task
      parameters:
        - in: path
          name: task_id
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: OK
        '401':
          description: Invalid or expired token
        '500':
          description: Internal error
  /tasks/page:
    get:
      summary: get tasks pagination
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                page_size:
                  type: integet
                page_number:
                  type: ingeger
      responses:
        '200':
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  title:
                    type: string
                  content:
                    type: string
        '401':
          description: Invalid or expired token
        '500':
          description: Internal error